"""first migration.

Revision ID: fe55a3e686ab
Revises: 
Create Date: 2024-05-01 23:30:10.770470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe55a3e686ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('agent_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_name'), ['name'], unique=True)

    op.create_table('chat_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idle_notification_time', sa.String(length=100), nullable=False),
    sa.Column('idle_notification_message', sa.String(length=300), nullable=False),
    sa.Column('idle_chat_end_time', sa.String(length=100), nullable=False),
    sa.Column('end_chat_message', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=100), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('upload_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template_message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('template')
    op.drop_table('share_template')
    op.drop_table('chat_setting')
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_name'))
        batch_op.drop_index(batch_op.f('ix_agent_email'))
        batch_op.drop_index(batch_op.f('ix_agent_agent_type'))

    op.drop_table('agent')
    # ### end Alembic commands ###
